version: 2
jobs:
  build-and-test:
    macos:
      xcode: 12.5.1
    environment: 
      FL_OUTPUT_DIR: output
    steps:
      - checkout:
      
      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: LargeProject
      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output
workflows:
    version: 2
    build_and_test:
        jobs:
          - build-and-test
